redis:
  image: redis

linked_persons:
  build: ./
  command: thin start --ssl --address 0.0.0.0 --port 443
  # command: bundle exec rackup -o 0.0.0.0 -p 9292
  ports:
    - "443:443"
  links:
    - redis
  stdin_open: true
  tty: true